config/routes.rb
Rails.application.routes.draw do

  devise_for :restaurants, controllers: {
    registrations: "restaurant/registrations",
    sessions: "restaurant/sessions",
    passwords: "restaurant/passwords"
  }
  
  devise_for :admins, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }
  
  devise_for :customers, controllers: {
    registrations: "public/registrations",
    sessions: "public/sessions",
    passwords: "public/passwords"
  }

  namespace :restaurant do
    resources :promotions, only: [:create, :destroy] do
      collection do
        get :promotion
      end
    end
    resources :coupons, only: [:index, :show, :create, :update, :destroy]
    resources :comments, only: [:index, :edit, :create, :update, :destroy]
    resources :owners, only: [:edit, :update] do
      member do
        patch :withdrawal
      end
      collection do
        get :unsubscribe
      end
    end
    get '/top' => 'homes#top'
  end
  
  namespace :admin do
    resources :genres, only: [:index, :edit, :create, :update, :destroy]
    resources :reviews, only: [:index, :destroy]
    resources :customers, only: [:index, :edit, :update, :destroy]
    resources :restaurants, only: [:edit, :update, :destroy]
    get '/top' => 'homes#top'
  end

  scope module: :public do
    resources :promotions, only: [:index]
    resources :restaurants, only: [:index, :show] do
      resources :reviews, only: [:index, :new, :show, :edit, :create, :update, :destroy] do
        resources :comments, only: [:edit, :create, :update, :destroy]
        resource :favorites, only: [:create, :destroy]
      end
    end
    resources :customers, only: [:show, :edit, :update] do
      member do
        patch 'customers/withdrawal'
        get 'customers/unsubscribe'
      end
    end
    get 'genre_search', to: 'searches#genre_search', as: 'genre_search'
    get 'keyword_search', to: 'searches#keyword_search', as: 'keyword_search'
  end
  
  get 'homes/top'
  root to: 'homes#top'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord

  belongs_to :customer
  belongs_to :review

  validates :body, presence: true

end

app/models/coupon.rb
class Coupon < ApplicationRecord

  belongs_to :restaurant


end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  geocoded_by :address
  after_validation :geocode, if: :address_changed?

  has_many :reviews, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  validates :last_name, presence: true
  validates :first_name, presence: true
  validates :last_name_kana, presence: true
  validates :first_name_kana, presence: true
  validates :nickname, presence: true
  validates :telephone_number, presence: true
  validates :postal_code, presence: true
  validates :address, presence: true

  def formatted_postal_code
    postal_code.insert(3, '-') if postal_code.present?
  end

  scope :active, -> { where(is_active: true) }

  # ログイン可能かどうかを確認
  def active_for_authentication?
    super && is_active
  end

  # 退会済みユーザーに対するカスタムメッセージ
  def inactive_message
    is_active ? super : :inactive
  end

end

app/models/favorite.rb
class Favorite < ApplicationRecord

  belongs_to :customer
  belongs_to :review

  validates :customer_id, uniqueness: { scope: :review_id }

end

app/models/genre.rb
class Genre < ApplicationRecord

  has_many :restaurants, dependent: :destroy

  validates :name, presence: true

end

app/models/promotion.rb
class Promotion < ApplicationRecord

  belongs_to :restaurant

  validates :name, presence: true
  validates :body, presence: true

  # 有効なプロモーションのみを取得するスコープ
  scope :active, -> { where("created_at > ?", 2.hours.ago) }

  # 期限切れのプロモーションを取得するスコープ
  scope :expired, -> { where("created_at <= ?", 2.hours.ago) }

end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  belongs_to :genre
  has_many :reviews, dependent: :destroy
  has_many :coupons, dependent: :destroy
  has_many :promotions, dependent: :destroy

  validates :name, presence: true
  validates :genre, presence: true
  validates :email, presence: true
  validates :postal_code, presence: true
  validates :address, presence: true
  validates :contact_number, presence: true
  validates :business_open_hours, presence: true
  validates :business_close_hours, presence: true
  validates :min_price, presence: true
  validates :max_price, presence: true
  validates :capacity, presence: true
  validates :parking_spaces, presence: true, if: :parking_lot?

  geocoded_by :address
  after_validation :geocode, if: :address_changed?

  def formatted_postal_code
    postal_code.insert(3, '-') if postal_code.present?
  end

  # ログイン可能かどうかを確認
  def active_for_authentication?
    super && is_active
  end

  # 退会済みユーザーに対するカスタムメッセージ
  def inactive_message
    is_active ? super : :inactive
  end

  scope :search_by_keyword, -> (keyword) {
    where("restaurants.name LIKE ? OR genres.name LIKE ? OR restaurants.address LIKE ?", "%#{keyword}%", "%#{keyword}%", "%#{keyword}%" ).joins(:genre)
  }

  scope :nearby, -> (latitude, longitude, distance) {
    near([latitude, longitude], distance, units: :km)
  }

  private
  
  def parking_lot?
    parking_lot == true
  end

end

app/models/review.rb
class Review < ApplicationRecord

  belongs_to :restaurant
  belongs_to :customer
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  validates :body, presence: true

  def favorited_by?(customer)
    return  false if customer.nil?
    favorites.exists?(customer_id: customer.id)
  end

end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  before_action :authenticate_admin!

  def index
    @genre = Genre.new
    @genres = Genre.all
  end

  def create
    if params[:genre].blank?
      @genres = Genre.all
      flash[:alert] = "ジャンルを入力してください。"
      render :index and return
    end

    @genre = Genre.new(genre_params)
    if @genre.save
      @genres = Genre.all
      flash[:notice] = "ジャンルを作成しました"
      redirect_to admin_genres_path
    else
      @genres = Genre.all
      flash.now[:alert] = "ジャンルの作成に失敗しました"
      render :index
    end
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    @genre = Genre.find(params[:id])
    if @genre.update(genre_params)
      flash[:notice] = "ジャンルを更新しました"
      redirect_to admin_genres_path
    else
      flash.now[:alert] = "ジャンルの更新に失敗しました"
      render :edit
    end
  end

  def destroy
    @genre = Genre.find(params[:id])
    @genre.destroy
    flash[:notice] = "ジャンルの削除に成功しました"
    redirect_to admin_genres_path
  end

  private
  def genre_params
    params.require(:genre).permit(:name)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/restaurants_helper.rb
module Admin::RestaurantsHelper
end

app/helpers/admin/reviews_helper.rb
module Admin::ReviewsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/restaurant/coupons_helper.rb
module Restaurant::CouponsHelper
end

app/helpers/restaurant/homes_helper.rb
module Restaurant::HomesHelper
end

app/helpers/restaurant/owners_helper.rb
module Restaurant::OwnersHelper
end

app/views/admin/genres/edit.html.erb
<div class="container py-5">
  <div class="row justify-content-center">
    <div class="col-12 col-md-10 col-lg-8">
      <div class="card shadow">
        <div class="card-body">
          <h4 class="card-title text-center mb-4">ジャンル一覧・作成</h4>

          <div class="card mb-3">
            <div class="card-body p-4">
              <%= render "layouts/errors", obj: @genre %>
              <%= form_with model: @genre, url: admin_genre_path(@genre), method: :patch, local: true do |f| %>
                <div class="input-group mb-3">
                  <span class="input-group-text"><%= f.label :name, "ジャンル名" %></span>
                  <%= f.text_field :name, class: "form-control" %>
                </div>
                <div class="d-grid gap-2 mb-4">
                <%= f.submit "更新", class: "btn btn-primary" %>
                </div>
              <% end %>
            </div>
          </div>

        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/genres/index.html.erb
<div class="container py-5">
  <div class="row justify-content-center">
    <div class="col-12 col-md-10 col-lg-8">
      <div class="card shadow">
        <div class="card-body">
          <h4 class="card-title text-center mb-4">ジャンル一覧・作成</h4>

          <div class="card mb-3">
            <div class="card-body p-4">
              <%= form_with model: @genre, url: admin_genres_path, local: true do |f| %>
              <%= render "layouts/errors", obj: @genre %>
                <div class="input-group mb-3">
                  <span class="input-group-text"><%= f.label :name, "ジャンル名" %></span>
                  <%= f.text_field :name, class: "form-control" %>
                </div>
                <div class="d-grid gap-2 mb-4">
                <%= f.submit "作成", class: "btn btn-primary" %>
                </div>
              <% end %>
            </div>
          </div>

          <div class="card">
            <div class="card-body">
              <div class="table-resposive">
                <table class="table w-75 mx-auto">
                  <thead>
                    <tr>
                      <th>ジャンル名</th>
                      <th>編集</th>
                      <th>削除</th>
                    </tr>
                  </thead>
                  <tbody>
                    <% @genres.each do |genre| %>
                      <tr>
                        <td><%= genre.name %></td>
                        <td><%= link_to '編集', edit_admin_genre_path(genre) %></td>
                        <td><%= link_to '削除', admin_genre_path(genre), method: :delete, data: { confirm: '本当に削除しますか？' } %></td>
                      </tr>
                    <% end %>
                  </tbody>
                </table>
              </div>
            </div>
          </div>

        </div>
      </div>
    </div>
  </div>
</div>