config/routes.rb
Rails.application.routes.draw do

  devise_for :restaurants, controllers: {
    registrations: "restaurant/registrations",
    sessions: "restaurant/sessions",
    passwords: "restaurant/passwords"
  }
  
  devise_for :admins, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }
  
  devise_for :customers, controllers: {
    registrations: "public/registrations",
    sessions: "public/sessions",
    passwords: "public/passwords"
  }

  namespace :restaurant do
    resources :promotions, only: [:create, :destroy] do
      collection do
        get :promotion
      end
    end
    resources :coupons, only: [:index, :show, :create, :update, :destroy]
    resources :comments, only: [:index, :edit, :create, :update, :destroy]
    resources :owners, only: [:edit, :update] do
      member do
        patch :withdrawal
      end
      collection do
        get :unsubscribe
      end
    end
    get '/top' => 'homes#top'
  end
  
  namespace :admin do
    resources :genres, only: [:index, :edit, :create, :update, :destroy]
    resources :reviews, only: [:index, :destroy]
    resources :customers, only: [:index, :edit, :update, :destroy]
    resources :restaurants, only: [:edit, :update, :destroy]
    get '/top' => 'homes#top'
  end

  scope module: :public do
    resources :promotions, only: [:index]
    resources :restaurants, only: [:index, :show] do
      resources :reviews, only: [:index, :new, :show, :edit, :create, :update, :destroy] do
        resources :comments, only: [:edit, :create, :update, :destroy]
        resource :favorites, only: [:create, :destroy]
      end
    end
    resources :customers, only: [:show, :edit, :update] do
      member do
        patch 'customers/withdrawal'
        get 'customers/unsubscribe'
      end
    end
    get 'genre_search', to: 'searches#genre_search', as: 'genre_search'
    get 'keyword_search', to: 'searches#keyword_search', as: 'keyword_search'
  end
  
  get 'homes/top'
  root to: 'homes#top'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  before_action :authenticate_admin!

  def top
    @restaurants = Restaurant.all
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/controllers/restaurant/homes_controller.rb
class Restaurant::HomesController < ApplicationController
  before_action :authenticate_restaurant!
  
  def top
    @restaurant = current_restaurant
  end
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/restaurant/homes_helper.rb
module Restaurant::HomesHelper
end

app/views/admin/homes/top.html.erb
<h2>登録店舗一覧</h2>


<table class="table">

  <thead>
    <tr>
      <th>店舗名</th>
      <th>住所</th>
      <th>ジャンル</th>
      <th>価格帯</th>
      <th>ステータス</th>
      <th>編集</th>
      <th>削除</th>
    </tr>
  </thead>
  
  <tbody>
    <% @restaurants.each do |restaurant| %>
      <tr>
        <td>
          <%= restaurant.name %>
        </td>
        <td>
          <%= restaurant.address %>
        </td>
        <td>
          <%= restaurant.genre.name %>
        </td>
        <td>
          <%= restaurant.min_price %>〜<%= restaurant.max_price %>円
        </td>
        <% if restaurant.is_active == true %>
          <td class="text-success">有効</td>
        <% else %>
          <td class="text-secondary">退会済</td>
        <% end %>
        <td>
          <%= link_to '編集', edit_admin_restaurant_path(restaurant), class: "btn btn-primary", data: { "turbolinks" => false } %>
        </td>
        <td>
          <%= link_to '削除', admin_restaurant_path(restaurant), method: :delete, class: "btn btn-danger", data: { confirm: '本当に削除しますか？' } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>