config/routes.rb
Rails.application.routes.draw do

  devise_for :restaurants, controllers: {
    registrations: "restaurant/registrations",
    sessions: "restaurant/sessions",
    passwords: "restaurant/passwords"
  }
  
  devise_for :admins, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }
  
  devise_for :customers, controllers: {
    registrations: "public/registrations",
    sessions: "public/sessions",
    passwords: "public/passwords"
  }

  namespace :restaurant do
    resources :promotions, only: [:create, :destroy] do
      collection do
        get :promotion
      end
    end
    resources :coupons, only: [:index, :show, :create, :update, :destroy]
    resources :comments, only: [:index, :edit, :create, :update, :destroy]
    resources :owners, only: [:edit, :update] do
      member do
        patch :withdrawal
      end
      collection do
        get :unsubscribe
      end
    end
    get '/top' => 'homes#top'
  end
  
  namespace :admin do
    resources :genres, only: [:index, :edit, :create, :update, :destroy]
    resources :reviews, only: [:index, :destroy]
    resources :customers, only: [:index, :edit, :update, :destroy]
    resources :restaurants, only: [:edit, :update, :destroy]
    get '/top' => 'homes#top'
  end

  scope module: :public do
    resources :promotions, only: [:index]
    resources :restaurants, only: [:index, :show] do
      resources :reviews, only: [:index, :new, :show, :edit, :create, :update, :destroy] do
        resources :comments, only: [:edit, :create, :update, :destroy]
        resource :favorites, only: [:create, :destroy]
      end
    end
    resources :customers, only: [:show, :edit, :update] do
      member do
        patch 'customers/withdrawal'
        get 'customers/unsubscribe'
      end
    end
    get 'genre_search', to: 'searches#genre_search', as: 'genre_search'
    get 'keyword_search', to: 'searches#keyword_search', as: 'keyword_search'
  end
  
  get 'homes/top'
  root to: 'homes#top'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  belongs_to :genre
  has_many :reviews, dependent: :destroy
  has_many :coupons, dependent: :destroy
  has_many :promotions, dependent: :destroy

  validates :name, presence: true
  validates :genre, presence: true
  validates :email, presence: true
  validates :postal_code, presence: true
  validates :address, presence: true
  validates :contact_number, presence: true
  validates :business_open_hours, presence: true
  validates :business_close_hours, presence: true
  validates :min_price, presence: true
  validates :max_price, presence: true
  validates :capacity, presence: true
  validates :parking_spaces, presence: true, if: :parking_lot?

  geocoded_by :address
  after_validation :geocode, if: :address_changed?

  def formatted_postal_code
    postal_code.insert(3, '-') if postal_code.present?
  end

  # ログイン可能かどうかを確認
  def active_for_authentication?
    super && is_active
  end

  # 退会済みユーザーに対するカスタムメッセージ
  def inactive_message
    is_active ? super : :inactive
  end

  scope :search_by_keyword, -> (keyword) {
    where("restaurants.name LIKE ? OR genres.name LIKE ? OR restaurants.address LIKE ?", "%#{keyword}%", "%#{keyword}%", "%#{keyword}%" ).joins(:genre)
  }

  scope :nearby, -> (latitude, longitude, distance) {
    near([latitude, longitude], distance, units: :km)
  }

  private
  
  def parking_lot?
    parking_lot == true
  end

end

app/controllers/admin/restaurants_controller.rb
class Admin::RestaurantsController < ApplicationController
  before_action :authenticate_admin!

  def edit
    @restaurant = Restaurant.find(params[:id])
  end

  def update

    if params[:restaurant][:parking_lot].blank?
      params[:restaurant][:parking_lot] = 'false'
    end

    if params[:restaurant][:parking_lot] == 'false' && params[:restaurant][:parking_spaces].present?
      params[:restaurant][:parking_spaces] = 0
    end
  

    @restaurant = Restaurant.find(params[:id])
    if params[:restaurant][:parking_lot] == 'false'
      params[:restaurant][:parking_spaces] = 0
    end
    # parking_lotがtrueの場合のみparking_spacesを必須にする
    if params[:restaurant][:parking_lot] == 'true' && params[:restaurant][:parking_lot].blank?
      @restaurant = build_resouce(sign_up_params)
      @restaurant.errors.add(parking_spaces, "は必須です")
      render :new
      return
    end

    if @restaurant.update(restaurant_params)
      flash[:notice] = "更新に成功しました"
      redirect_to admin_top_path
    else
      flash.now[:alert] = "更新に失敗しました"
      render :edit
    end
  end

  def destroy
    @restaurant = Restaurant.find(params[:id])
    @restaurant.destroy
    flash[:notice] = "店舗の削除に成功しました"
    redirect_to admin_top_path
  end

  private

  def restaurant_params
    params.require(:restaurant).permit(
      :name,
      :genre_id,
      :email,
      :postal_code,
      :address,
      :contact_number,
      :business_open_hours,
      :business_close_hours,
      :min_price,
      :max_price,
      :capacity,
      :parking_lot,
      :parking_spaces,
      :is_active
    )
  end

end

app/controllers/restaurant/confirmations_controller.rb
# frozen_string_literal: true

class Restaurant::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/restaurant/homes_controller.rb
class Restaurant::HomesController < ApplicationController
  before_action :authenticate_restaurant!
  
  def top
    @restaurant = current_restaurant
  end
end

app/controllers/restaurant/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Restaurant::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/restaurant/owners_controller.rb
class Restaurant::OwnersController < ApplicationController
  before_action :authenticate_restaurant!
  before_action :is_matching_login_restaurant, only: [:edit, :update, :unsubscribe, :withdrawal]
  
  def edit
    @owner = current_restaurant
  end

  def update
    @owner = current_restaurant
    if @owner.update(restaurant_params)
      flash[:notice] = "店舗情報を更新しました。"
      redirect_to restaurant_top_path
    else
      flash.now[:alert] = "店舗情報の更新に失敗しました。"
      render :edit
    end
  end

  def unsubscribe
    @owner = current_restaurant
  end

  def withdrawal
    @owner = current_restaurant
    @owner.update(is_active: false)
    reset_session
    flash[:notice] = "退会処理が完了しました。"
    redirect_to root_path
  end

  private

  def restaurant_params
    params.require(:restaurant).permit(
      :name,
      :genre_id,
      :email,
      :postal_code,
      :address,
      :contact_number,
      :business_open_hours,
      :business_close_hours,
      :min_price,
      :max_price,
      :capacity,
      :parking_lot,
      :parking_spaces
    )
  end

  def is_matching_login_restaurant
    @restaurant = Restaurant.find(params[:id])
    unless @restaurant == current_restaurant
      redirect_to restaurant_top_path(current_restaurant)
    end
  end

end

app/controllers/restaurant/passwords_controller.rb
# frozen_string_literal: true

class Restaurant::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/restaurant/promotions_controller.rb
class Restaurant::PromotionsController < ApplicationController
  before_action :authenticate_restaurant!
  before_action :is_matching_login_restaurant, only: [:destroy]


  def promotion
    @promotion = Promotion.new
    @promotions = current_restaurant.promotions.active
  end

  def create
    @promotion = current_restaurant.promotions.new(promotion_params)
    if current_restaurant.promotions.active.exists?
      flash.now[:alert] = "アクションは1件のみ作成できます。新しいアクションを作成したい場合は現在のアクションを削除してください。"
      @promotions = current_restaurant.promotions.active
      render :promotion
    elsif @promotion.save
      flash[:notice] = "アクションを作成しました。"
      @promotions = current_restaurant.promotions.active
      redirect_to promotion_restaurant_promotions_path
    else
      flash.now[:alert] = "アクションの作成に失敗しました。"
      @promotions = current_restaurant.promotions.active
      render :promotion
    end
  end

  def destroy
    @promotion = Promotion.find(params[:id])
    @promotion.destroy
    flash[:notice] = "アクションの削除に成功しました。"
    redirect_to promotion_restaurant_promotions_path
  end

  private
  
  def promotion_params
    params.require(:promotion).permit(:name, :body)
  end

  def is_matching_login_restaurant
    @restaurant = restaurant.find(params[:id])
    unless @restaurant == current_restaurant
      redirect_to restaurant_top_path(current_restaurant)
    end
  end

end

app/controllers/restaurant/registrations_controller.rb
# frozen_string_literal: true

class Restaurant::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  def create
    if params[:restaurant][:parking_lot] == false
      params[:restaurant][:parking_spaces] = 0
    end
    # parking_lotがtrueの場合のみparking_spacesを必須にする
    if params[:restaurant][:parking_lot] == true && params[restaraunt][parking_lot].blank?
      @restaurant = build_resouce(sign_up_params)
      @restaurant.errors.add(parking_spaces, "は必須です")
      render :new
      return
    end

    super # 他の処理（ユーザー作成処理）をそのまま呼び出す
  end

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [
      :name, 
      :genre_id,
      :postal_code, 
      :address, 
      :contact_number, 
      :business_open_hours, 
      :business_close_hours, 
      :min_price, 
      :max_price, 
      :capacity, 
      :parking_lot, 
      :parking_spaces
    ])
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/restaurant/sessions_controller.rb
# frozen_string_literal: true

class Restaurant::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  def after_sign_in_path_for(resource)
    restaurant_top_path
  end

  def after_sign_out_path_for(resource)
    root_path
  end

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/restaurant/unlocks_controller.rb
# frozen_string_literal: true

class Restaurant::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/admin/restaurants_helper.rb
module Admin::RestaurantsHelper
end

app/helpers/restaurant/comments_helper.rb
module Restaurant::CommentsHelper
end

app/helpers/restaurant/coupons_helper.rb
module Restaurant::CouponsHelper
end

app/helpers/restaurant/homes_helper.rb
module Restaurant::HomesHelper
end

app/helpers/restaurant/owners_helper.rb
module Restaurant::OwnersHelper
end

app/helpers/restaurant/promotions_helper.rb
module Restaurant::PromotionsHelper
end

app/views/restaurant/owners/edit.html.erb
<div class="container py-5">
  <div class="row justify-content-center">
    <div class="col-12 col-md-8 col-lg-6">
      <div class="card shadow">
        <div class="card-body p-4">
          <h2 class="card-title text-center mb-4">店舗情報編集</h2>

          <%= render 'layouts/errors', obj: @owner %>

          <%= form_with model: @owner, url: restaurant_owner_path(@owner), method: :patch, local: true do |f| %>
            <%# 基本情報 %>
            <div class="card mb-4">
              <div class="card-header bg-light">
                <h5 class="mb-0">基本情報</h5>
              </div>
              <div class="card-body">
                <div class="mb-3">
                  <%= f.label :name, "店舗名", class: "form-label" %>
                  <div class="input-group">
                    <span class="input-group-text"><i class="fas fa-store"></i></span>
                    <%= f.text_field :name, class: "form-control" %>
                  </div>
                </div>

                <div class="mb-3">
                  <%= f.label :genre_id, "ジャンル", class: "form-label" %>
                  <%= f.collection_select :genre_id, Genre.all, :id, :name, 
                      { prompt: "選択してください" }, 
                      { class: "form-select" } %>
                </div>

                <div class="mb-3">
                  <%= f.label :email, "メールアドレス", class: "form-label" %>
                  <div class="input-group">
                    <span class="input-group-text"><i class="fas fa-envelope"></i></span>
                    <%= f.email_field :email, class: "form-control" %>
                  </div>
                </div>
              </div>
            </div>

            <%# 住所・連絡先 %>
            <div class="card mb-4">
              <div class="card-header bg-light">
                <h5 class="mb-0">住所・連絡先</h5>
              </div>
              <div class="card-body">
                <div class="mb-3">
                  <%= f.label :postal_code, "郵便番号（ハイフンなし）", class: "form-label" %>
                  <div class="input-group">
                    <span class="input-group-text"><i class="fas fa-map-marker-alt"></i></span>
                    <%= f.text_field :postal_code, class: "form-control" %>
                  </div>
                </div>

                <div class="mb-3">
                  <%= f.label :address, "住所", class: "form-label" %>
                  <div class="input-group">
                    <span class="input-group-text"><i class="fas fa-home"></i></span>
                    <%= f.text_field :address, class: "form-control" %>
                  </div>
                </div>

                <div class="mb-3">
                  <%= f.label :contact_number, "電話番号", class: "form-label" %>
                  <div class="input-group">
                    <span class="input-group-text"><i class="fas fa-phone"></i></span>
                    <%= f.text_field :contact_number, class: "form-control" %>
                  </div>
                </div>
              </div>
            </div>

            <%# 営業情報 %>
            <div class="card mb-4">
              <div class="card-header bg-light">
                <h5 class="mb-0">営業情報</h5>
              </div>
              <div class="card-body">
                <div class="row g-3">
                  <div class="col-md-6">
                    <%= f.label :business_open_hours, "営業開始時間", class: "form-label" %>
                    <%= f.text_field :business_open_hours, class: "form-control" %>
                  </div>
                  <div class="col-md-6">
                    <%= f.label :business_close_hours, "営業終了時間", class: "form-label" %>
                    <%= f.text_field :business_close_hours, class: "form-control" %>
                  </div>
                </div>

                <div class="row g-3 mt-2">
                  <div class="col-md-6">
                    <%= f.label :min_price, "最小価格", class: "form-label" %>
                    <div class="input-group">
                      <%= f.text_field :min_price, class: "form-control" %>
                      <span class="input-group-text">円</span>
                    </div>
                  </div>
                  <div class="col-md-6">
                    <%= f.label :max_price, "最大価格", class: "form-label" %>
                    <div class="input-group">
                      <%= f.text_field :max_price, class: "form-control" %>
                      <span class="input-group-text">円</span>
                    </div>
                  </div>
                </div>

                <div class="mb-3 mt-3">
                  <%= f.label :capacity, "収容人数", class: "form-label" %>
                  <div class="input-group">
                    <%= f.text_field :capacity, class: "form-control" %>
                    <span class="input-group-text">人</span>
                  </div>
                </div>

                <div class="mb-3">
                  <%= f.label :parking_lot, "駐車場", class: "form-label d-block" %>
                  <div class="btn-group" role="group">
                    <%= f.radio_button :parking_lot, true, id: "parking_yes", 
                        class: "btn-check" %>
                    <%= f.label :parking_lot_yes, "有", for: "parking_yes", 
                        class: "btn btn-outline-primary" %>
                    
                    <%= f.radio_button :parking_lot, false, id: "parking_no", 
                        class: "btn-check" %>
                    <%= f.label :parking_lot_no, "無", for: "parking_no", 
                        class: "btn btn-outline-primary" %>
                  </div>
                </div>

                <div id="parking_capacity_field" class="mb-3" style="display: none;">
                  <%= f.label :parking_spaces, "駐車可能台数", class: "form-label" %>
                  <div class="input-group">
                    <%= f.text_field :parking_spaces, class: "form-control" %>
                    <span class="input-group-text">台</span>
                  </div>
                </div>
              </div>
            </div>

            <%# 更新ボタン %>
            <div class="d-grid gap-2">
              <%= f.submit "更新する", class: "btn btn-success btn-lg" %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/restaurant/owners/unsubscribe.html.erb
<h2>退会確認画面</h2>

<p>本当に退会しますか？</p>

<p>退会するとアカウントおよびすべてのデータが削除されます。</p>
<p>再度ご利用いただくには、新しいアカウントを作成する必要があります。</p>

<%= link_to '戻る', restaurant_path(current_restaurant), class: 'btn btn-primary' %>
<%= link_to '退会する', withdrawal_restaurant_owner_path(current_restaurant), method: :patch, class: 'btn btn-danger' %>